[profile.default]
src = 'contracts/src'
out = 'out'
test = 'contracts/test'
libs = ['contracts/lib']

[rpc_endpoints]
goerli = "${GOERLI_RPC_URL}"

# See more config options https://github.com/foundry-rs/foundry/tree/master/config